ФЗ9
Kiril1KinG/java-filmorate pull request #4
Opened 2023-10-31 02:22 UTC by Kiril1KinG

Первая версия ФЗ 9 спринта :B

2023-10-31 18:16 UTC, kalitva requested changes

2023-10-31 18:16 UTC, kalitva commented on .gitignore
> -db/*
Верни эти две линии, пригодятся когда будем с бд работать

2023-10-31 18:16 UTC, kalitva commented on pom.xml
> +	<parent>
Замени табы на отступы по 4 пробела

2023-10-31 18:16 UTC, kalitva commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
Удали коммент

2023-10-31 18:16 UTC, kalitva commented on pom.xml
> +	<description>Бэкенд для сервиса, который будет работать с фильмами и оценками пользователей, а также возвращать топ-5 фильмов, рекомендованных к просмотру.</description>
Описание на английском пожалуйста

2023-10-31 18:16 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate FIRST_MOVIE = LocalDate.of(1895, 12, 28);
Статические поля обычно объявляются перед публичными

2023-10-31 18:16 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean valid(Film film) {
1. Приватные методы объявляются после публичных
2. Лучше `valid --> validateReleaseDate`
3. И давай `ValidationException` выбрасывать прямо из этого метода (сделав его `void`)

2023-10-31 18:16 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getData() {
`getData --> getFilms`
Избегай таких абстрактных имен, которые ни о чем неговорят, типа `data, value` и .т. д.

2023-10-31 18:16 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
Инвертируй условие и избавься от ненужного `else`

```java
        if (!data.containsKey(film.getId())) {
            throw new DataNotFoundException("Фильм не найден");
        } 
        data.put(film.getId(), film);
        return film;
```

https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp

2023-10-31 18:16 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            data.put(++currentId, film);
То же самое, везде исправь `data`  на имя, описывающее контент

2023-10-31 18:16 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else if (user.getName().isBlank()) {
Объедини эти два условия в одно с помощью `||`

2023-10-31 18:16 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ValidationException("Логин не может сожержать пробелы");
Логи и сообщения для исключений везде по английски

2023-10-31 18:55 UTC, Kiril1KinG commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else if (user.getName().isBlank()) {
Здесь я специально их изначально разделил, потому что user.getName().isBlank() выкидывал NPE при тестах, сейчас после твоего комментария опять попробовал, но в другом порядке, сначала проверку на null а потом на пустую строку, в таком случае не выкидывает, играюсь в idea, опять меняю порядок и опять NPE.
Джава настолько ленивая, что при логическом "||" откидывает остальные условия при первом true?)

2023-11-01 18:35 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Integer, Film> films = new HashMap();
private

2023-11-01 18:36 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        }
Переделай таким же образом, как переделал `updateFilm`

2023-11-01 23:58 UTC, merged