ФЗ11 add-database
Kiril1KinG/java-filmorate pull request #7
Opened 2023-11-18 01:41 UTC by Kiril1KinG

Картинка и ссылочка на ERD в README

2023-11-18 17:27 UTC, kalitva requested changes

2023-11-18 17:27 UTC, kalitva commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jpa</artifactId>
Спринг дата нам пока не нужна, удали зависимость

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmService.java
> +    private final LikeDbStorage likeDbStorage;
Нет лайк-дао нам не нужно, методы по лайкам - в фильмах

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmService.java
>      public Film addLike(int filmId, int userId) {
Сделай метод void

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/Service/UserService.java
> +    private final FriendshipDbStorage friendshipDbStorage;
То же самое с эти дао - логика по друзьям в юзерах

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +import lombok.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это затрудняет чтение, засоряет git diff'ы и иногда может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

https://blog.marcnuri.com/intellij-idea-how-to-disable-wildcard-imports

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(int id, String name, String description, LocalDate releaseDate, long duration, Mpa mpa) {
Чем этот конструктор отличается от того, который сгенерил ломбок? Вообще поудаляй конструкторы из моделей , они только мешают

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +import lombok.*;
Проверь везде чтобы не было wildcard импортов

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        validateFilm(film, "Add");
Что за валидация? Все валидации должны быть в сервисах, здесь только достать\сохранить из бд

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        List<Integer> id = jdbcTemplate.query("SELECT film_id FROM film WHERE name = ? AND release_date = ?",
Не надо дополнительным запросом извлекать сгенеренный айди, почитай как сделать

https://www.baeldung.com/spring-jdbc-autogenerated-keys

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (filmId.size() != 1) {
Проверяй наличие фильма в сервисе, вызовом метода `containsFilmById`

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "f.release_date release_date, f.duration duration, f.rating_id rating_id, r.name rating_name " +
`SELECT * FROM films f`, нет необходимости перечислять все поля

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        return films.stream().sorted(Comparator.comparingInt(Film::getId)).collect(Collectors.toList());
Сортировать нужно на уровне бд (`ORDER BY`)

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    }
```java
        try {
            return Optional.of(jdbcTemplate.queryForObject(FIND_BY_ID_QUERY, this::mapFilm, id));
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
```

Используй `JdbcTemplate#queryForObject` если надо достать один объект

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    }
Используй `COUNT`, нет необходимости мапить весь объект, чтобы узнать о его наличии

```java
        Long count = jdbcTemplate.queryForObject("SELECT COUNT(1) FROM films", Long.class, id);
        return count == 1
```

2023-11-18 17:27 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private RowMapper<Film> filmRowMapper() {
Преобразуй сигнатуру метода, чтобы его можно было передавать в `query` как лямбду-референс

2023-11-19 03:37 UTC, Kiril1KinG commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "f.release_date release_date, f.duration duration, f.rating_id rating_id, r.name rating_name " +
Тут есть необходимость перечислять поля, так как сджойнены таблицы film и rating с одинаковым полем name

2023-11-20 22:15 UTC, Kiril1KinG commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        for (User u : users) {
Тут не понял как ты имел в виду использовать batchUpdate, этот метод только достаёт значения из таблиц, чтобы присвоить объекту, ничего не вставляет

2023-11-21 22:08 UTC, kalitva approved these changes

2023-11-21 22:08 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/Service/FilmService.java
> +            jdbcTemplate.queryForObject("SELECT rating_id FROM rating WHERE rating_id = ?", Integer.class,
Нет, нельзя ни в коем случае писать sql прямо в сервисе, делегируй в методы стораджа все, что касается БД

2023-11-28 14:03 UTC, merged